### ISSUE TITLE
The download link is broken

### ISSUE THREAD

**Issue by NNNNAI** [epic-kitchens/C5-Multi-Instance-Retrieval#2]
I hope all is well with you😊. The download link of features extracted using TBN is broken. Could you please solve it?😊
Thanks again, have a nice day~~

**Comment by mwray** [comment]
Sorry about that, I will try and update the link though this might take a while to upload the features as they are quite large.
We have the temporally averaged/maxed features available [here](https://www.dropbox.com/s/bs6y50xkl1rbe20/JPoSE_data.zip?dl=0) If you're able to use these in the meanwhile.

Thanks,
Michael

**Comment by mwray** [comment]
This has now been fixed in [9bb06be](https://github.com/epic-kitchens/C5-Multi-Instance-Retrieval/commit/9bb06bec2216595da53d383e4d5eca353f3862ad), the links should now take you to dropbox to download the TBN features. Please see the readme for more details as to the structure of these features.
