### ISSUE TITLE
Download link for HowTo100M S3D features is broken?

### ISSUE THREAD

**Issue by vineetparikh** [epic-kitchens/C5-Multi-Instance-Retrieval#3]
Hi there,

I'm trying to get the features for Epic Kitchens from a pretrained S3D off of HowTo100M, and it looks like this repository has it. However, for some reason the download link appears to be broken: would you be able to help me out here?

Thanks so much for your help,
Vineet

**Comment by adrianofragomeni** [comment]
Sorry for the problem. 
All the links work now.

**Comment by vineetparikh** [comment]
Thanks so much! For context: are these video features extracted with S3D? I'm basically trying to run VideoCLIP with Epic-Kitchens and they expect S3D features, but their expected structure is a little different: how are the .npy files structured in this download?

**Comment by adrianofragomeni** [comment]
We used the following code to extract the features https://github.com/antoine77340/S3D_HowTo100M.

In the npy files you can find the features of all the action clips of train and test sets of Epic-Kitchens for the retrieval task: https://github.com/epic-kitchens/epic-kitchens-100-annotations/tree/master/retrieval_annotations.

 The order follows the original dataframes you can find here: https://github.com/epic-kitchens/epic-kitchens-100-annotations/tree/master/retrieval_annotations.
